image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose build --no-cache
    - docker-compose push
