services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION}
    environment:
      APP_VERSION: ${APP_VERSION}
    ports:
      - "8080:80"